version: '3.5'
services:
  web-integra14:
    #image: odoo:14
    build:
      context: .
    container_name: integra14_container
    depends_on:
      - db-integra14
    ports:
      - "15000:8069"
    volumes:
      - odoo-web-integra14:/var/lib/odoo
      - ./config:/etc/odoo
      - ./enterprise:/mnt/extra-addons
      - ./modules:/mnt/custom-addons
      - ./custom:/mnt/another-addons
    environment:
      - PYTHONUNBUFFERED=0
  db-integra14:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-integra14:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-integra14:
  odoo-db-integra14: